remotedir:  remote_directory

slurm:
  nodes: 1
  cpus-per-task: 1
  job-name: docksing_test

container:
  image:  alpine:latest
  commands: ["sh -c","'echo $salerno > /output/output.txt'"]
  environment:
    - TEST: hello
    - GOOGLE_APPLICATION_CREDENTIALS: a_token
    - salerno: reggio_calabria
  volumes:
    - /home/gangelotti/projects/docksing/examples/remote_directory/output:/output

