remotedir:  remote_directory

slurm:
  nodes: 1
  cpus-per-task: 1
  job-name: docksing_test

container:
  image:  experiment
  commands: ["hello",">","output.txt"]
  environment:
    - TEST: hello__world
    - GOOGLE_APPLICATION_CREDENTIALS: hello!
    - salerno: reggio_calabria
  ports:
    - 8080:8080
